version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    volumes:
      - .:/var/www/html/car-app
      - /var/www/html/car-app/vendor
      - ./storage:/var/www/html/car-app/storage
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    working_dir: /var/www/html/car-app
    command: php artisan serve --host=0.0.0.0 --port=8000